// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReceiptsProcessed struct {
	ProcessedID int32  `json:"processed_id"`
	ReceiptID   *int32 `json:"receipt_id"`
	UserID      *int32 `json:"user_id"`
	Data        []byte `json:"data"`
}

type ReceiptsRaw struct {
	ReceiptID int32  `json:"receipt_id"`
	UserID    *int32 `json:"user_id"`
	OcrText   string `json:"ocr_text"`
}

type User struct {
	UserID     int32              `json:"user_id"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
	Email      string             `json:"email"`
	Password   string             `json:"password"`
	DateJoined pgtype.Timestamptz `json:"date_joined"`
}
